### ISSUE TITLE
Add RAF browser prefixing

### ISSUE THREAD

**Issue by nickjacob** [rivertam/manage-scroll-handlers#1]
Right now you just look for `window.requestAnimationFrame` -- some browsers used prefix fn name:

``` javascript
var raf = win.requestAnimationFrame
  || win.webkitRequestAnimationFrame
  || win.mozRequestAnimationFrame
  || win.msRequestAnimationFrame
  || function(cb) { return setTimeout(cb, 16); };
```

from [fastdom](https://github.com/wilsonpage/fastdom/blob/master/fastdom.js) source

**Comment by rivertam** [comment]
Thanks for taking a look. When implementing this, I checked out [caniuse](http://caniuse.com/#search=requestanimation), which implies no browsers currently support browser prefixes and not general `requestAnimationFrame`, so I chose not to add those fallbacks.
